services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: task_app
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        environment:
            - COMPOSER_ALLOW_SUPERUSER=1
        networks:
            - laravel-network

    webserver:
        image: nginx:latest
        container_name: laravel_webserver
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - laravel-network

volumes:
    db-data:

networks:
    laravel-network:
        driver: bridge
